name: Publish
on:
  push:
    branches:
      - main
jobs:
  Publish:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Publish
        run: cargo publish --allow-dirty || echo "Cargo publish failed, continuing..."
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}

      - name: Get Version
        id: get_version
        run: echo "VERSION=$(grep '^version =' Cargo.toml | cut -d' ' -f3 | tr -d '\"')" >> $GITHUB_ENV

      - name: Define Binary Name
        id: define_binary
        run: echo "BIN_NAME=yt-feeds-v${{ env.VERSION }}-linux-amd64" >> $GITHUB_ENV;

      - name: Build Binary
        id: build_binary
        run: cargo build --release

      - name: Rename Binary
        id: rename_binary
        run: mv target/release/yt-feeds target/release/${{ env.BIN_NAME }};          

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binaries
        id: upload_binaries
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/${{ env.BIN_NAME }},
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
